# -*- coding: utf-8 -*-
"""face_attendence_data_Set_prepration.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13lEF1tLfmxOwYhvIdL-IV1twRTC4RoNc
"""

# Commented out IPython magic to ensure Python compatibility.
# %cd "/content/drive/MyDrive/attendence data"

!ls

import pandas as pd
import os
import numpy as np
import shutil

columns = ["S.No","name","email","image_location","h","i","j","k","Location","Year","physical IP","IP","Browser","l","m","Address","device","status"]
df = pd.read_csv("/content/drive/MyDrive/attendence data/Livinglab.csv", names = columns)
df.head()

data = df.iloc[0: ,0:3]

data.to_csv('/content/drive/MyDrive/attendence data/data.csv')

data = pd.read_csv("/content/drive/MyDrive/attendence data/data.csv")

data.head()

data.rename(columns= {"S.No":"Name","name":"email","email":"file_location"}, inplace= True)

data.head()

data["Name"] = data["Name"].str.lower()
data.head()

data.to_csv("/content/drive/MyDrive/attendence data/final_data.csv")

df = pd.read_csv("/content/drive/MyDrive/attendence data/final_data.csv")

data.head()

#data["file_location"] = data['file_location'].map(lambda x: x.lstrip('uploads/'))
#data.head()

file_names = list(data['file_location'].values)
img_labels = list(data['Name'].values)

file_names

folders_to_be_created = np.unique(img_labels)

source = os.getcwd()

for new_path in folders_to_be_created:
    if not os.path.exists(".//" + new_path):
        os.makedirs(new_path)

folders = folders_to_be_created.copy()

for f in range(len(file_names)):

  current_img = file_names[f]
  current_label = img_labels[f]
  shutil.move(current_img,current_label)

